name: Piper

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Python Build
        uses: SAP/project-piper-action@main
        with:
          piper-version: devel:SAP:jenkins-library:2cad9b8
          command: pythonBuild
